# Generated by Django 2.2.5 on 2019-09-14 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_auto_20190913_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'Course'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'Student'},
        ),
    ]
