# Generated by Django 2.2.5 on 2019-09-15 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20190915_1638'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseRegistration',
        ),
    ]
